# **Numpy**
- Numpy stand for Numerical Python.
- Numpy was created in 2005 by Travis Oliphant.
- Numpy is the fundamental package for scientist computing in python.
- Numpy is a python library that provides a multidimensional array object, various derived objects.

# **Array**
An array is a data structure that stores values of same data type. In python, this is the main difference between arrays and lists while python list can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

# **Alias **
In python alias are an alternate name for referring to the same thing.


In [1]:
# Creating Numpy array - To create numpy array we use np.array()
import numpy as np
# 1D Array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# 3D Array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("3D Array:\n", arr3)

# Higher dimensional array
arrn =np.array([1, 2, 3, 4], ndmin=5)
print("Higher dimensional array:\n", arrn)


1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Higher dimensional array:
 [[[[[1 2 3 4]]]]]


In [2]:
# Properties of arrays :-

# 1. Homogeneity - All elements in a NumPy array must be of the same data type (e.g., int, float, bool).
import numpy as np
arr = np.array([1, 2, 3])
print("Data Type :", arr.dtype)

# 2. Shape - The shape of an array is a tuple that indicates the number of elements in each dimension (rows, columns, etc.).
print("Shape of array :",arr.shape)

# 3. Size - The total number of elements in the array.
print("Size of array :",arr.size)

# 4. Dimensionality - The number of dimensions of the array. A 1D array has a single axis, a 2D array has two axes (rows and columns), and so on.
print("Dimensional of an array : " ,arr1.ndim)
print("Dimensional of an array :",arr2.ndim)
print("Dimensional of an array :",arr3.ndim)

# 5. Data Type (dtype) - Specifies the data type of the elements in the array. NumPy supports a variety of data types, such as int, float, bool, and complex.
print("Data Type of an array :",arr.dtype)

# 6. Reshape - Reshape changes the structure of an array without altering the data.
reshaped = arr2.reshape(3, 2)
print("Reshaped array: ", reshaped)

# 7. Transpose - Transpose flips the axes of the array.
transposed = arr2.T
print("Transposed: ", transposed)

#8. Copy- A copy creates a new array with its own data.
copy = arr.copy()
copy[0]=25
print("arr after copy modification:", arr)

# 9.View - A view is a new array object that refers to the same data as the original array.
view = arr.view()
view[0]=25
print("arr after view modification:", arr)




Data Type : int64
Shape of array : (3,)
Size of array : 3
Dimensional of an array :  1
Dimensional of an array : 2
Dimensional of an array : 3
Data Type of an array : int64
Reshaped array:  [[1 2]
 [3 4]
 [5 6]]
Transposed:  [[1 4]
 [2 5]
 [3 6]]
arr after copy modification: [1 2 3]
arr after view modification: [25  2  3]


**Copy vs View**

*Copy*
- The copy owns the data
- Any changes made to the copy will not affect original array
- Any changes made to the original array will not affect the copy.

*View*

- The view does not own the data.
- Any changes made to the view will affect the original array.
- Any changes made to the original array will affect the view.

In [3]:
# Special Numpy array
#1. Zeros Array (numpy.zeros)- Creates an array filled with zeros. Useful for initializing arrays when the default value is zero.
# 1D Array of Zeros
import numpy as np
ar_zero=np.zeros(4)
print("1D Zeros Array:",ar_zero)

# 2D Array of Zeros
ar_zero2=np.zeros((2,3))
print("2D Zeros Array:\n",ar_zero2)

# 2. Ones Array (numpy.ones) - Creates an array filled with ones. Often used for initialization when a value of one is required.
# 1D Array of Ones
ar_ones = np.ones(4)
print("1D Ones Array:", ar_ones)

# 2D Array of Ones
ar_ones2 = np.ones((3,2))
print("2D Ones Array: \n", ar_ones2)

# 3D Array of ones
ar_ones3 = np.ones((2,3,4))
print("3D Ones Array: \n", ar_ones3)

# 3. Empty Array (numpy.empty) - Creates an uninitialized array of the specified shape and type.The array elements contain random values. Useful when performance is critical, and the array will be fully populated later.

# 1D Array of Empty
ar_empty = np.empty(4)
print("1D Ones Array:", ar_empty)

# 2D Array of Empty
ar_empty2 = np.empty((3,2))
print("2D Ones Array: \n", ar_empty2)

# 3D Array of Empty
ar_empty3 = np.empty((2,3,4))
print("3D Ones Array: \n", ar_empty3)

# 4. Arange Array (numpy.arange)- Creates an array with evenly spaced values within a given range. Similar to Python’s range but returns a NumPy array.
# Default Start, Step
arange_default = np.arange(8)
print("Arange Default:", arange_default)

# Specified Start, Stop, Step
arange_custom = np.arange(1, 10, 2)
print("Arange Custom:", arange_custom)

# 5. Identity Matrix (numpy.eye) - Creates a 2D square matrix with ones on the main diagonal and zeros elsewhere.Useful in linear algebra and matrix computations.
# Square Identity Matrix
identity = np.eye(4)
print("Identity Matrix:\n", identity)

# Rectangular Identity Matrix
rectangular_identity = np.eye(3, 4)
print("Rectangular Identity Matrix:\n", rectangular_identity)

# Diagonal
diag= np.eye(4, k=1)
print("Diagonal:\n", diag)

# linspace -The numpy.linspace function is used to create arrays with evenly spaced values between a specified start and stop value.
# Generate 10 evenly spaced numbers between 0 and 1
arr_lin = np.linspace(0, 1, 10)
print("Linspace Array:", arr_lin)

# Generate 10 numbers between 0 and 1, excluding the endpoint
arr_lin1 = np.linspace(0, 1, 10, endpoint=False)
print("Linspace Array Without Endpoint:", arr_lin1)

# Generate 5 numbers between 0 and 10 and return the step size
array, step = np.linspace(0, 10, 5, retstep=True)
print("Array:", array)
print("Step Size:", step)

















1D Zeros Array: [0. 0. 0. 0.]
2D Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
1D Ones Array: [1. 1. 1. 1.]
2D Ones Array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
3D Ones Array: 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
1D Ones Array: [1. 1. 1. 1.]
2D Ones Array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
3D Ones Array: 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Arange Default: [0 1 2 3 4 5 6 7]
Arange Custom: [1 3 5 7 9]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Rectangular Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
Diagonal:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
Linspace Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Linspace Array Without Endpoint: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
Array: [ 0.   2.5  5.   7.5 10. ]
Step Size: 2.5


### **Creating NumPy Arrays with Random Numbers**
- NumPy provides the numpy.random module to generate arrays with random numbers. This module offers various functions to generate random data for different distributions and use cases.

In [4]:
# 1. Random Numbers from Uniform Distribution (numpy.random.rand) - Generates random numbers between 0 and 1 from a uniform distribution.Values are evenly distributed over the interval [0, 1).
import numpy as np

# 1D Array of Random Numbers
random_1d = np.random.rand(10)
print("1D Array of Random Numbers:", random_1d)

# 2D Array of Random Numbers
random_2d = np.random.rand(4, 5)
print("2D Array of Random Numbers:\n", random_2d)

# 2. Random Integers (numpy.random.randint) - Generates random integers from a specified range [low, high). Optionally specify the shape of the output array.
# Random Integers between 10 and 20
random_int = np.random.randint(10, 20, size=(3, 4))
print("Random Integers:\n", random_int)

# 3. Random Numbers from Normal Distribution (numpy.random.randn) - Generates random numbers from the standard normal distribution (mean=0, standard deviation=1).Values are sampled from a normal (Gaussian) distribution.
# 1D Array from Standard Normal Distribution
random_normal = np.random.randn(5)
print("1D Array from Normal Distribution:", random_normal)

# 2D Array from Standard Normal Distribution
random_normal_2d = np.random.randn(3, 3)
print("2D Array from Normal Distribution:\n", random_normal_2d)

# 4. Random Numbers from a Custom Uniform Range (numpy.random.uniform) - Generates random numbers from a uniform distribution within a specified range [low, high).
# Random Numbers Between 5 and 10
random_uniform = np.random.uniform(5, 10, size=(2, 3))
print("Random Numbers from Custom Uniform Range:\n", random_uniform)

# 5. Random Choice from a List or Array (numpy.random.choice) - Randomly selects elements from a given array or list.Can specify whether sampling should be with or without replacement.
# Random Selection from a List
arr_rand = [10, 20, 30, 40, 50,60,70]
random_choice = np.random.choice(arr_rand, size=3, replace=False)
print("Random Choice:", random_choice)

# 6. Random Numbers with Fixed Seed (numpy.random.seed) - Sets the seed for reproducibility of random numbers.
# Setting the Seed
np.random.seed(42)
random_seed = np.random.rand(6)
print("Random Numbers with Fixed Seed:", random_seed)

# 7. Random Numbers from Other Distributions
# (i) Normal Distribution with Custom Mean and Standard Deviation
mean = 15
std_dev = 4
random_normal = np.random.normal(mean, std_dev, size=(3, 3))
print("Random Numbers from Normal Distribution:\n", random_normal)

 # (ii) Binomial Distribution
n, p = 10, 0.5  # Number of trials and probability of success
random_binomial = np.random.binomial(n, p, size=5)
print("Random Numbers from Binomial Distribution:", random_binomial)

# (iii) Poisson Distribution
Lam = 3  # Lambda parameter
random_poisson = np.random.poisson(Lam, size=5)
print("Random Numbers from Poisson Distribution:", random_poisson)

1D Array of Random Numbers: [0.81272404 0.97774466 0.97392029 0.33670095 0.57007226 0.79899098
 0.36373156 0.64561126 0.63619246 0.19631459]
2D Array of Random Numbers:
 [[0.78265121 0.76640581 0.38757105 0.40974218 0.98931239]
 [0.63660173 0.35063134 0.85035081 0.16320199 0.45130253]
 [0.64694783 0.34590085 0.12479445 0.04721367 0.13549362]
 [0.30341755 0.80470839 0.17281034 0.54550309 0.61780369]]
Random Integers:
 [[11 11 11 15]
 [14 10 19 15]
 [18 14 16 14]]
1D Array from Normal Distribution: [-0.39786339  0.48413037  1.22375616  0.16101174 -2.27318418]
2D Array from Normal Distribution:
 [[ 0.26130002  0.35672479  1.27112476]
 [ 1.03439246  0.51568904 -0.29822544]
 [ 1.02696602 -0.6793226   0.82805479]]
Random Numbers from Custom Uniform Range:
 [[5.21561318 8.77885826 7.81868266]
 [9.5875207  5.9714858  9.04998736]]
Random Choice: [20 40 60]
Random Numbers with Fixed Seed: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
Random Numbers from Normal Distribution:

## **Broadcasting Numpy Array**
- Broadcasting is a powerful feature in NumPy that allows arrays with different shapes to perform arithmetic operations together.
- Instead of creating large replicated arrays, NumPy automatically "broadcasts" the smaller array to match the shape of the larger array, optimizing performance and memory usage.


### **Rule 1: Dimensions Compatibility**

- If two arrays differ in their shape, the shape with fewer dimensions is padded with ones on its left side until both shapes have the same number of dimensions.

### **Rule 2: Size Compatibility**

- Two dimensions are compatible when:
1.They are equal, or

2.One of them is 1.

### **Rule 3: Resulting Shape**

- The resulting shape is the maximum size along each dimension.

### **4. Error**

- If the dimensions do not meet these criteria, a broadcasting error occurs.

In [5]:
# 1. Scalar and Array - A scalar is broadcast to match the shape of an array.
import numpy as np

# Scalar and 1D Array
arr_1d = np.array([1, 2, 3])
scalar = 2
print("Addition of Scalar and 1D Array:", arr_1d +scalar)

# 2. Two Arrays with Compatible Shapes
# 2D Array and 1D Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Addition of 2D array and 1D array:\n", arr_1d + arr_2d)


Addition of Scalar and 1D Array: [3 4 5]
Addition of 2D array and 1D array:
 [[2 4 6]
 [5 7 9]]


In [6]:
# Broadcasting Rules in Action
# 1 Different Shapes
import numpy as np
a = np.array([[1], [2], [3]])  # Shape (3, 1)
b = np.array([10, 20, 30, 40])  # Shape (1, 4)
print("Addition of (3,1) and (1,4) shape array:\n", a + b )

# 2 Incompatible Shapes
#c = np.array([[1, 2], [3, 4], [5, 6]])  # Shape (3, 2)
#d = np.array([[10, 20, 30], [40, 50, 60]])  # Shape (2, 3)

# This will raise a ValueError
# Reason:- The shapes (3, 2) and (2, 3) are not compatible for broadcasting because their dimensions do not satisfy the broadcasting rules.
# print("Addition of incompatible shape :", c + d)

# Normalizing Data- Broadcasting can normalize a 2D array by subtracting the mean and dividing by the standard deviation along columns.
data = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
mean = data.mean(axis=0)
std_dev = data.std(axis=0)
normalized_data = (data - mean) / std_dev
print("Normalized Data:\n", normalized_data)

# Element-wise multiplication of different shaped arrays
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
result = a * b
print("Element-wise multiplication :\n", a*b)



Addition of (3,1) and (1,4) shape array:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
Normalized Data:
 [[-1. -1. -1.]
 [ 1.  1.  1.]]
Element-wise multiplication :
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


## **Indexing and Slicing in NumPy Arrays**
- Indexing and slicing in NumPy arrays allow you to access and modify specific elements, rows, columns, or subarrays of an array. This feature makes it easy to manipulate and extract subsets of data.


In [7]:
#  Indexing in NumPy Arrays
# 1D Array Indexing - Similar to Python lists, indexing starts from 0.
import numpy as np

# Create a 1D array
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])

print("Access First Element:", arr_1d[0])
print("Access Last Element:", arr_1d[-1])

 # 2D Array Indexing -Use two indices: one for rows and one for columns.
 # Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at Row 1, Column 2:", arr_2d[0, 1])
print("Element at Row 3, Column 3:", arr_2d[2, 2])

# 3D Array Indexing- Use three indices: one for depth, one for rows, and one for columns.
# Create a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Element at Depth 1, Row 2, Column 1:", arr_3d[0, 1, 0])
print("Element at Depth 2, Row 2, Column 2:", arr_3d[1, 1, 1])



Access First Element: 10
Access Last Element: 70
Element at Row 1, Column 2: 2
Element at Row 3, Column 3: 9
Element at Depth 1, Row 2, Column 1: 3
Element at Depth 2, Row 2, Column 2: 8


In [8]:
# Slicing in NumPy Arrays- Slicing allows you to extract subarrays using the syntax
# 1D Array Slicing
# Create a 1D array

# Extract subsets
print("First 3 Elements:", arr_1d[:3])
print("Last 2 Elements:", arr_1d[-2:])
print("Every Other Element:", arr_1d[::2])

# 2D Array Slicing - Slice rows and columns separately using :.
# Create a 2D array

# Extract subsets
print("First Row:", arr_2d[0, :])
print("First Column:", arr_2d[:, 0])
print("Subarray (Rows 1-2, Columns 2-3):\n", arr_2d[0:2, 1:3])

# 3D Array Slicing - Slice depth, rows, and columns separately.
# Create a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Extract subsets
print("All Elements from Depth 1:\n", arr_3d[0, :, :])

print("First Column of All Depths:\n", arr_3d[:, :, 0])



First 3 Elements: [10 20 30]
Last 2 Elements: [60 70]
Every Other Element: [10 30 50 70]
First Row: [1 2 3]
First Column: [1 4 7]
Subarray (Rows 1-2, Columns 2-3):
 [[2 3]
 [5 6]]
All Elements from Depth 1:
 [[1 2]
 [3 4]]
First Column of All Depths:
 [[1 3]
 [5 7]]


In [9]:
# Boolean Indexing - Boolean indexing allows you to filter elements based on conditions.
# Create an array
array = np.array([10, 15, 20, 25, 30])

# Filter elements greater than 20
filtered = array[array > 20]
print("Filtered Elements:", filtered)


Filtered Elements: [25 30]


In [10]:
#  Fancy Indexing - Fancy indexing allows you to access elements using arrays of indices.
# Create an array
array = np.array([10, 20, 30, 40, 50, 60, 70])

# Access elements at specific positions
indices = [0, 2, 4]
print("Selected Elements:", array[indices])
 # For 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access specific rows and columns
rows = [0, 1, 2]
cols = [2, 1, 0]
print("Fancy Indexing Result:", array_2d[rows, cols])

Selected Elements: [10 30 50]
Fancy Indexing Result: [3 5 7]


### **Iterating Over NumPy Arrays**
Iterating means going through elements one by one. As we deal with multi-dimensional arrays in numpy, we can do this using basis **for** loop of python.
- If we iterate on a 1D array it will go through each element one by one.
- In 2D array it will go through all the rows.
- In a 3D array it will go through all the 2D-arrays.
- In a nD array it will go through (n-1)th D one by one.

In [11]:
# 1. Iterating Over 1D Arrays- For 1D arrays, iteration works similarly to iterating over a Python list.
# Create a 1D array

# Iterate using a loop
for element in arr_1d:
    print(element)

# 2. Iterating Over 2D Arrays - When iterating over 2D arrays, the loop iterates through rows by default
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterate over rows
for row in array_2d:
    print(row)

# 3. Iterating Over Individual Elements (Flattened Array)- To iterate over each element, you can use the numpy.nditer() function or flatten the array.
# Iterate using nditer
for element in np.nditer(array_2d):
    print(element, end=" ")

# Flattening the Array
# Iterate over flattened array
for element in array_2d.flatten():
    print(element, end=" ")

# 4. Iterating Over 3D Arrays- For higher-dimensional arrays, iteration follows the same principle: looping over the "outermost" arrays.
# Create a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Iterate over 2D arrays
for matrix in array_3d:
    print(matrix)

# Iterating Over All Elements in 3D Arrays
# Use nditer to iterate over all elements
for element in np.nditer(array_3d):
    print(element, end=" ")

# 5. Modifying Array Elements During Iteration- To modify array elements during iteration, you can use the op_flags=['readwrite'] argument in nditer.
# Modify elements during iteration
for element in np.nditer(array_2d, op_flags=['readwrite']):
    element[...] = element * 2  # Multiply each element by 2

print("Modified Array:\n", array_2d)

# 6. Iterating with Conditions- You can iterate and apply conditions using a loop or NumPy's boolean indexing.
# Using Loops
# Print only elements greater than 4
for element in np.nditer(array_2d):
    if element > 4:
        print(element, end=" ")

# Using Boolean Indexing
# Print only elements greater than 4
print(array_2d[array_2d > 4])

# 7. Iterating with Index Tracking (numpy.ndenumerate)- To track both the index and the value, use numpy.ndenumerate.
# Track index and value
for index, value in np.ndenumerate(array_2d):
    print(f"Index: {index}, Value: {value}")

# 8. Iterating with Step Size-You can specify a step size for iteration using slicing.
# Iterate with a step size
for element in array_2d[::2, ::2]:  # Skip every other row and column
    print(element)

# 9. Vectorized Operations vs. Iteration-While iteration is useful, vectorized operations are generally faster and more efficient in NumPy.
# Add 10 to every element (vectorized)
array_2d += 10
print(array_2d)




10
20
30
40
50
60
70
[1 2 3]
[4 5 6]
[7 8 9]
1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9 [[1 2]
 [3 4]]
[[5 6]
 [7 8]]
1 2 3 4 5 6 7 8 Modified Array:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
6 8 10 12 14 16 18 [ 6  8 10 12 14 16 18]
Index: (0, 0), Value: 2
Index: (0, 1), Value: 4
Index: (0, 2), Value: 6
Index: (1, 0), Value: 8
Index: (1, 1), Value: 10
Index: (1, 2), Value: 12
Index: (2, 0), Value: 14
Index: (2, 1), Value: 16
Index: (2, 2), Value: 18
[2 6]
[14 18]
[[12 14 16]
 [18 20 22]
 [24 26 28]]


## **Enumerated Iteration in NumPy Using numpy.ndenumerate**
- Enumeration means mentioning sequence number of something one by one.
- Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [12]:
# Create a 1D array

# Enumerate indices and values
for index, value in np.ndenumerate(arr_1d):
    print(f"Index: {index}, Value: {value}")

# Create a 2D array

# Enumerate indices and values
for index, value in np.ndenumerate(arr_2d):
    print(f"Index: {index}, Value: {value}")

# Create a 3D array

# Enumerate indices and values
for index, value in np.ndenumerate(array_3d):
    print(f"Index: {index}, Value: {value}")

# Double the value of elements greater than 3
for index, value in np.ndenumerate(arr_2d):
    if value > 3:
        arr_2d[index] = value * 2

print("Modified Array:\n", arr_2d)

Index: (0,), Value: 10
Index: (1,), Value: 20
Index: (2,), Value: 30
Index: (3,), Value: 40
Index: (4,), Value: 50
Index: (5,), Value: 60
Index: (6,), Value: 70
Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9
Index: (0, 0, 0), Value: 1
Index: (0, 0, 1), Value: 2
Index: (0, 1, 0), Value: 3
Index: (0, 1, 1), Value: 4
Index: (1, 0, 0), Value: 5
Index: (1, 0, 1), Value: 6
Index: (1, 1, 0), Value: 7
Index: (1, 1, 1), Value: 8
Modified Array:
 [[ 1  2  3]
 [ 8 10 12]
 [14 16 18]]


In [13]:
# Comparing ndenumerate with enumerate
# enumerate works for 1D arrays or lists but is less effective for multi-dimensional arrays. ndenumerate is designed specifically for multi-dimensional NumPy arrays.

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Using enumerate (less intuitive for multi-dimensions)
for i, row in enumerate(array_2d):
    for j, value in enumerate(row):
        print(f"Value: {value} at Index: ({i}, {j})")

# Using ndenumerate (simpler and more intuitive)
for index, value in np.ndenumerate(array_2d):
    print(f"Value: {value} at Index: {index}")

Value: 1 at Index: (0, 0)
Value: 2 at Index: (0, 1)
Value: 3 at Index: (0, 2)
Value: 4 at Index: (1, 0)
Value: 5 at Index: (1, 1)
Value: 6 at Index: (1, 2)
Value: 1 at Index: (0, 0)
Value: 2 at Index: (0, 1)
Value: 3 at Index: (0, 2)
Value: 4 at Index: (1, 0)
Value: 5 at Index: (1, 1)
Value: 6 at Index: (1, 2)


# **Join Functions**
- Joining means putting contents of two or more arrays in as single array.
- We pass a sequence of arrays that we want to join to the concatenate() function along with the axis, if axis is not explicitly passed, it is taken as 0.

In [14]:
# np.concatenate()- Combines two or more arrays along an existing axis.
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))
print(result)

# Joining 2D Arrays -
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Join along rows (axis=0)
result_row = np.concatenate((arr1, arr2), axis=0)
print("Join along axis=0: \n",result_row)

# Join along columns (axis=1)
result_col= np.concatenate((arr1, arr2.T), axis=1)
print("Join along axis=1:\n",result_col)

[1 2 3 4 5 6]
Join along axis=0: 
 [[1 2]
 [3 4]
 [5 6]]
Join along axis=1:
 [[1 2 5]
 [3 4 6]]


# **Joining arrays using stack function**

- Stacking is same as concatenation, the only difference is that stackng is done along a new axis.
- We can concatenate two 1D arrays along the second axis which would result in putting them one over the other
- We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.


In [15]:
# 1 numpy.vstack (Vertical Stack)-Stacks arrays vertically (row-wise).
# Vertical stacking
result = np.vstack((arr1, arr2))
print("Vertical Stack:\n", result)

#  Vertical stacking
result = np.vstack((arr1, arr2))
print("Vertical Stack:\n", result)

# 3 numpy.dstack (Depth Stack)-Stacks arrays along a new third axis.
# Create arrays
arr4 = np.array([[1, 2], [3, 4]])
arr5 = np.array([[5, 6], [7, 8]])

# Depth stacking
result = np.dstack((arr4, arr5))
print("Depth Stack:\n", result)

# 4 numpy.column_stack- Stacks 1D arrays as columns into a 2D array.
# Create 1D arrays
arr6 = np.array([1, 2, 3])
arr7 = np.array([4, 5, 6])

# Column stacking
result = np.column_stack((arr6, arr7))
print("Column Stack:\n", result)

# 5 numpy.row_stack-Stacks 1D arrays as rows into a 2D array (alias for vstack).
# Row stacking
result = np.row_stack((arr6, arr7))
print("Row Stack:\n", result)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]
Depth Stack:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Column Stack:
 [[1 4]
 [2 5]
 [3 6]]
Row Stack:
 [[1 2 3]
 [4 5 6]]


# **Splitting NumPy Arrays**

- Splitting is reverse operation of joining. Joining merges multiple arrays into one.
- Splitting breaks one array into multiple.
- Splitting involves dividing an array into multiple sub-arrays.
- We use array_split() for splitting arrays, We pass it the array we want to split and the number of splits.
-  NumPy provides several functions for this:


In [16]:
# 1 numpy.split - Splits an array into multiple sub-arrays.
# Create array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Split into 2 parts along axis=1 (columns)
result = np.split(arr, 2)
print("Split Result:\n", result)

# 2 numpy.array_split - Splits an array into sub-arrays of unequal size.
# Unequal splitting
result = np.array_split(arr, 3, axis=1)
print("Unequal Split:\n", result)

# numpy.hsplit (Horizontal Split) - Splits an array horizontally (column-wise).
# Horizontal split
result = np.hsplit(arr, 3)
print("Horizontal Split:\n", result)

# 4 numpy.vsplit (Vertical Split) - Splits an array vertically (row-wise).
# Vertical split
result = np.vsplit(arr, 2)
print("Vertical Split:\n", result)

# 5 numpy.dsplit (Depth Split) - Splits an array along the third axis.
# Create 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Depth split
result = np.dsplit(arr_3d, 2)
print("Depth Split:\n", result)

Split Result:
 [array([[1, 2, 3]]), array([[4, 5, 6]])]
Unequal Split:
 [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
Horizontal Split:
 [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
Vertical Split:
 [array([[1, 2, 3]]), array([[4, 5, 6]])]
Depth Split:
 [array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


### **NumPy Array Functions: Search, Sort, Searchsorted, and Filter**
1. **Search Functions**
- You can search an array for a certain value, and return the indexes that get a match.
- To search an array, use the where() method.

2. **Sorting Functions**
- Sorting arranges the elements of an array in ascending or descending order.
- Sorting means putting elements in an ordered sequence.
- Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
- The Numpy ndarray object has a function called sort() that will sort a specified array.

3. **numpy.searchsorted**
- There is a method called searchsorted() which performs a binary search in the array and return the index where the specified value would be inserted to maintain the search order.
- Searches for the indices where elements should be inserted to maintain order in a sorted array.
  **Search from the right side**
  - By default the left most index is returned, but we can give side='right' to return the right most index instead.
4. **Filtering Functions**
- Filtering allows you to extract elements based on conditions.
- Getting some elements out of an existing array and creating a new array out of them is called filtering.
- In Numpy you filter an array using a boolean index list.
- If the value at an index is **True** that element is contained in the filtered array, if the value at that index if **False** that element is excluded from the filtered array.

In [17]:
#  Search Functions

# 1 numpy.where - Finds indices of elements that satisfy a condition.
import numpy as np

# Array
arr = np.array([10, 20, 30, 40, 50])

# Find indices where values are greater than 25
result = np.where(arr > 25)
print("Indices where values > 25:", result)

# Replace values: if > 25, replace with 100; otherwise, replace with 0
modified = np.where(arr > 25, 100, 0)
print("Modified array:", modified)

# 2 numpy.nonzero - Finds the indices of non-zero elements in an array.
arr = np.array([0, 1, 2, 0, 3, 0, 4])

# Get non-zero indices
result = np.nonzero(arr)
print("Non-zero indices:", result)

# 3 numpy.argwhere- Finds the indices of elements that satisfy a condition, but returns a 2D array of indices.
arr = np.array([[10, 20], [30, 40], [50, 60]])

# Find indices where values are > 30
result = np.argwhere(arr > 30)
print("Indices where values > 30:\n", result)

Indices where values > 25: (array([2, 3, 4]),)
Modified array: [  0   0 100 100 100]
Non-zero indices: (array([1, 2, 4, 6]),)
Indices where values > 30:
 [[1 1]
 [2 0]
 [2 1]]


In [18]:
#   Sorting Functions

# 1 numpy.sort- Sorts an array along a specified axis.
arr = np.array([[3, 2, 1], [6, 5, 4]])

# Sort each row
sorted_arr = np.sort(arr, axis=1)
print("Row-wise sorted array:\n", sorted_arr)

# Sort each column
sorted_arr = np.sort(arr, axis=0)
print("Column-wise sorted array:\n", sorted_arr)

# 2 numpy.argsort- Returns the indices that would sort an array.
arr = np.array([30, 10, 20])

# Get indices to sort the array
sorted_indices = np.argsort(arr)
print("Indices to sort the array:", sorted_indices)

# Sort using the indices
sorted_arr = arr[sorted_indices]
print("Sorted array:", sorted_arr)



Row-wise sorted array:
 [[1 2 3]
 [4 5 6]]
Column-wise sorted array:
 [[3 2 1]
 [6 5 4]]
Indices to sort the array: [1 2 0]
Sorted array: [10 20 30]


In [19]:
#  numpy.searchsorted

sorted_array = np.array([10, 20, 30, 40])

# Find insertion indices
indices = np.searchsorted(sorted_array, [25, 35])
print("Indices for insertion:", indices)

# Using 'right' side
indices = np.searchsorted(sorted_array, [25, 35], side='right')
print("Indices for insertion (right side):", indices)

Indices for insertion: [2 3]
Indices for insertion (right side): [2 3]


In [20]:
#  Filtering Functions

# 1 Filtering with Boolean Indexing - You can directly use conditions to filter arrays.
arr = np.array([10, 20, 30, 40, 50])

# Filter elements greater than 25
filtered = arr[arr > 25]
print("Filtered array:", filtered)

# 2 numpy.extract - Extracts elements that satisfy a condition.
# Extract elements greater than 25
condition = arr > 25
result = np.extract(condition, arr)
print("Extracted elements:", result)

# 3 Custom Filtering with numpy.vectorize - Use numpy.vectorize to apply a function to each element.

# Define a custom filter function
def is_even(x):
    return x % 2 == 0

# Apply the function to the array
vectorized = np.vectorize(is_even)
result = arr[vectorized(arr)]
print("Filtered even numbers:", result)


Filtered array: [30 40 50]
Extracted elements: [30 40 50]
Filtered even numbers: [10 20 30 40 50]


# **NumPy Array Functions: Shuffle, Unique, Resize, Flatten, and Ravel**

1. **Shuffle Function (numpy.random.shuffle)**
- The shuffle() method takes a sequence, like a list and recoganize the order of the items.
- Shuffle means changing arrangement of elements in place i.e. in the array itself.

2. **Unique Function (numpy.unique)**
- Finds the unique elements of an array, optionally returning their indices and counts.
- The unique() function is used to find the unique elements of an array.Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements
- The indices of the input array that give the unique values.
- The indices of the unique array that reconstruct the input array.
- The number of times each unique value comes up in the input array.

3. **Resize Function (numpy.resize)**
- Resizes an array to a new shape. If the new size is larger, the array is repeated to fill the space.
- The resize() function is used to create a new array with the specified shape. If the new array is larger than the original array, then the new array is filled with repeated copies.

4. **Flatten Function (numpy.ndarray.flatten)**
- Flattens a multi-dimensional array into a 1D array. It always returns a copy.
- The flatten() function is used to get a copy of an given array collapsed into one dimension.

5. **Ravel Function (numpy.ravel)**
- Returns a flattened view of the array (if possible), avoiding copying data unless necessary.

In [21]:
# import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Shuffle the array
np.random.shuffle(arr)
print("Shuffled array:\n", arr)

# Create an array with duplicates
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])

# Find unique elements
unique_elements = np.unique(arr)
print("Unique elements:", unique_elements)

# Find unique elements with counts
unique_elements, counts = np.unique(arr, return_counts=True)
print("Unique elements with counts:", unique_elements, counts)

# Create an array
arr = np.array([1, 2, 3, 4])

# Resize to a 3x3 array (elements repeat)
resized = np.resize(arr, (3, 3))
print("Resized array:\n", resized)


# Create a 2D array
arr = np.array([[1, 2], [3, 4]])

# Flatten the array
flattened = arr.flatten()
print("Flattened array:", flattened)

# Create a 2D array
arr = np.array([[1, 2], [3, 4]])

# Ravel the array
raveled = np.ravel(arr)
print("Raveled array:", raveled)

Shuffled array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Unique elements: [1 2 3 4 5]
Unique elements with counts: [1 2 3 4 5] [1 2 1 3 1]
Resized array:
 [[1 2 3]
 [4 1 2]
 [3 4 1]]
Flattened array: [1 2 3 4]
Raveled array: [1 2 3 4]


# **Insert and Delete Functions in NumPy**

1. **Insert Function**
- The insert() function is used to insert values along the given axis before the given indices.

2. **Delete Function**
- The delete() function return a new array with sub-arrays along an axis deleted. For a one-dimensional array, this returns those entries not returned by arr[obj]

In [22]:
# 1. Insert Function (numpy.insert) - The numpy.insert function inserts values into an array at specified indices. It creates a new array without modifying the original.
#  Insert into a 1D Array

import numpy as np


# Original array
arr = np.array([1, 2, 3, 4, 5])

# Insert value 10 at index 2
new_arr = np.insert(arr, 2, 10)
print("Original array:", arr)
print("Array after insertion:", new_arr)

#  Insert into a 2D Array
# Original 2D array
arr_2d = np.array([[1, 2], [3, 4]])

# Insert a new row [5, 6] at index 1
new_arr_2d = np.insert(arr_2d, 1, [5, 6], axis=0)
print("Array after row insertion:\n", new_arr_2d)

# Insert a new column [7, 8, 9] at index 1
new_arr_2d_col = np.insert(new_arr_2d, 1, [7, 8, 9], axis=1)
print("Array after column insertion:\n", new_arr_2d_col)



Original array: [1 2 3 4 5]
Array after insertion: [ 1  2 10  3  4  5]
Array after row insertion:
 [[1 2]
 [5 6]
 [3 4]]
Array after column insertion:
 [[1 7 2]
 [5 8 6]
 [3 9 4]]


In [23]:
# 2. Delete Function (numpy.delete) - The numpy.delete function removes elements from an array at specified indices. It creates a new array without modifying the original.
# 1 Delete from a 1D Array
# Original array
arr = np.array([1, 2, 3, 4, 5])

# Delete element at index 2
new_arr = np.delete(arr, 2)
print("Original array:", arr)
print("Array after deletion:", new_arr)

# 2 Delete from a 2D Array
# Original 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Delete the second row (index 1)
new_arr_2d = np.delete(arr_2d, 1, axis=0)
print("Array after row deletion:\n", new_arr_2d)

# Delete the first column (index 0)
new_arr_2d_col = np.delete(new_arr_2d, 0, axis=1)
print("Array after column deletion:\n", new_arr_2d_col)



Original array: [1 2 3 4 5]
Array after deletion: [1 2 4 5]
Array after row deletion:
 [[1 2 3]
 [7 8 9]]
Array after column deletion:
 [[2 3]
 [8 9]]
